/*GENERATED BY OBNC 0.16.1*/

#include "extArgs.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "ArgsTest.obn"

static char arg_[8];

static char shortArg_[2];

static char appName_[1024];

static OBNC_INTEGER res_;

#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	extArgs__Init();
	OBNC_ASSERT(extArgs__count_ == 2, "ArgsTest.obn", 29);
	extArgs__Get_(0, arg_, 8, &res_);
	OBNC_ASSERT(OBNC_CMP(arg_, 8, "foo", 4) == 0, "ArgsTest.obn", 32);
	OBNC_ASSERT(res_ == 0, "ArgsTest.obn", 33);
	extArgs__Get_(1, arg_, 8, &res_);
	OBNC_ASSERT(OBNC_CMP(arg_, 8, "bar", 4) == 0, "ArgsTest.obn", 36);
	OBNC_ASSERT(res_ == 0, "ArgsTest.obn", 37);
	extArgs__Get_(0, shortArg_, 2, &res_);
	OBNC_ASSERT(OBNC_CMP(shortArg_, 2, "f", 2) == 0, "ArgsTest.obn", 40);
	OBNC_ASSERT(res_ == 2, "ArgsTest.obn", 41);
	extArgs__GetAppName_(appName_, 1024, &res_);
	OBNC_ASSERT(OBNC_CMP(appName_, 1024, "./AppTest", 10) != 0, "ArgsTest.obn", 44);
	OBNC_ASSERT(res_ == 0, "ArgsTest.obn", 45);
	return 0;
}
