/*GENERATED BY OBNC 0.16.1*/

#include "extConvert.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "ConvertTest.obn"

static char s_[32];

static char shortStr_[2];

static OBNC_INTEGER i_;

static OBNC_REAL x_;

static int done_;

static int ApproxEqual_(OBNC_REAL x_, OBNC_REAL y_)
{
	return OBNC_ABS_FLT(x_ - y_) < 0.00100000000000000002;
}


#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	extConvert__Init();
	extConvert__IntToString_(-123, s_, 32, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 36);
	OBNC_ASSERT(OBNC_CMP(s_, 32, "-123", 5) == 0, "ConvertTest.obn", 37);
	extConvert__IntToString_(0, s_, 32, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 39);
	OBNC_ASSERT(OBNC_CMP(s_, 32, "0", 2) == 0, "ConvertTest.obn", 40);
	extConvert__IntToString_(123, s_, 32, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 42);
	OBNC_ASSERT(OBNC_CMP(s_, 32, "123", 4) == 0, "ConvertTest.obn", 43);
	extConvert__IntToString_(123, shortStr_, 2, &done_);
	OBNC_ASSERT(! done_, "ConvertTest.obn", 45);
	extConvert__RealToString_(-123.0, s_, 32, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 49);
	OBNC_ASSERT((OBNC_CMP(s_, 32, "-1.230000E+02", 14) == 0) || (OBNC_CMP(s_, 32, "-1.230000E+002", 15) == 0), "ConvertTest.obn", 50);
	extConvert__RealToString_(0.0, s_, 32, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 52);
	OBNC_ASSERT((OBNC_CMP(s_, 32, "0.000000E+00", 13) == 0) || (OBNC_CMP(s_, 32, "0.000000E+000", 14) == 0), "ConvertTest.obn", 53);
	extConvert__RealToString_(123.0, s_, 32, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 55);
	OBNC_ASSERT((OBNC_CMP(s_, 32, "1.230000E+02", 13) == 0) || (OBNC_CMP(s_, 32, "1.230000E+002", 14) == 0), "ConvertTest.obn", 56);
	extConvert__RealToString_(123.0, shortStr_, 2, &done_);
	OBNC_ASSERT(! done_, "ConvertTest.obn", 58);
	extConvert__StringToInt_("-123", 5, &i_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 62);
	OBNC_ASSERT(i_ == -123, "ConvertTest.obn", 63);
	extConvert__StringToInt_("0", 2, &i_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 65);
	OBNC_ASSERT(i_ == 0, "ConvertTest.obn", 66);
	extConvert__StringToInt_("123", 4, &i_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 68);
	OBNC_ASSERT(i_ == 123, "ConvertTest.obn", 69);
	extConvert__StringToInt_("0FFH", 5, &i_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 71);
	OBNC_ASSERT(i_ == 255, "ConvertTest.obn", 72);
	extConvert__StringToInt_("foo123", 7, &i_, &done_);
	OBNC_ASSERT(! done_, "ConvertTest.obn", 74);
	extConvert__StringToReal_("-12.3", 6, &x_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 78);
	OBNC_ASSERT(ApproxEqual_(x_, -12.3000000000000007), "ConvertTest.obn", 79);
	extConvert__StringToReal_("0.0", 4, &x_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 81);
	OBNC_ASSERT(ApproxEqual_(x_, 0.0), "ConvertTest.obn", 82);
	extConvert__StringToReal_("1.23E+01", 9, &x_, &done_);
	OBNC_ASSERT(done_, "ConvertTest.obn", 84);
	OBNC_ASSERT(ApproxEqual_(x_, 12.3000000000000007), "ConvertTest.obn", 85);
	extConvert__StringToReal_("foo12.3", 8, &x_, &done_);
	OBNC_ASSERT(! done_, "ConvertTest.obn", 87);
	return 0;
}
