/*GENERATED BY OBNC 0.16.1*/

#include "extEnv.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "EnvTest.obn"

static void Test_(void)
{
	char foo_[8];
	char foo1_[4];
	OBNC_INTEGER res_;

	extEnv__Get_("FOO", 4, foo_, 8, &res_);
	OBNC_ASSERT(res_ == 0, "EnvTest.obn", 28);
	OBNC_ASSERT(OBNC_CMP(foo_, 8, "bar baz", 8) == 0, "EnvTest.obn", 29);
	extEnv__Get_("FOO", 4, foo1_, 4, &res_);
	OBNC_ASSERT(res_ == 4, "EnvTest.obn", 32);
	OBNC_ASSERT(OBNC_CMP(foo1_, 4, "bar", 4) == 0, "EnvTest.obn", 33);
	extEnv__Get_("ENVTESTFOO", 11, foo_, 8, &res_);
	OBNC_ASSERT(res_ == -1, "EnvTest.obn", 36);
}


#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	extEnv__Init();
	Test_();
	return 0;
}
