/*GENERATED BY OBNC 0.16.1*/

#include "extErr.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "ErrTest.obn"

#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	extErr__Init();
	extErr__Char_('a');
	extErr__Ln_();
	extErr__String_("abc", 4);
	extErr__Ln_();
	extErr__Int_((-2147483647 - 1), 0);
	extErr__Ln_();
	extErr__Int_(-1, 0);
	extErr__Ln_();
	extErr__Int_(-1, 3);
	extErr__Ln_();
	extErr__Int_(0, 0);
	extErr__Ln_();
	extErr__Int_(1, 0);
	extErr__Ln_();
	extErr__Int_(37, 0);
	extErr__Ln_();
	extErr__Int_(2147483647, 0);
	extErr__Ln_();
	extErr__Hex_(0);
	extErr__Ln_();
	extErr__Hex_(1);
	extErr__Ln_();
	extErr__Hex_(-559038737);
	extErr__Ln_();
	extErr__Real_(-1.0, 0);
	extErr__Ln_();
	extErr__Real_(0.0, 0);
	extErr__Ln_();
	extErr__Real_(0.0, 14);
	extErr__Ln_();
	extErr__Real_(1.0, 0);
	extErr__Ln_();
	extErr__Real_(37.0, 0);
	extErr__Ln_();
	extErr__Real_(0.369999999999999996, 0);
	extErr__Ln_();
	return 0;
}
