/*GENERATED BY OBNC 0.16.1*/

#ifndef extArgs_h
#define extArgs_h

#include <obnc/OBNC.h>

#define extArgs__count_ ext__extArgs__count_
extern OBNC_INTEGER extArgs__count_;

#define extArgs__Get_ ext__extArgs__Get_
void extArgs__Get_(OBNC_INTEGER n_, char arg_[], OBNC_INTEGER arg_len, OBNC_INTEGER *res_);

#define extArgs__GetAppName_ ext__extArgs__GetAppName_
void extArgs__GetAppName_(char arg_[], OBNC_INTEGER arg_len, OBNC_INTEGER *res_);

#define extArgs__Init ext__extArgs__Init
void extArgs__Init(void);

#endif
