/*GENERATED BY OBNC 0.16.1*/

#include "extArgs.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "extArgs.obn"

OBNC_INTEGER extArgs__count_;

void extArgs__Get_(OBNC_INTEGER n_, char arg_[], OBNC_INTEGER arg_len, OBNC_INTEGER *res_)
{
}


void extArgs__GetAppName_(char arg_[], OBNC_INTEGER arg_len, OBNC_INTEGER *res_)
{
}


void extArgs__Init(void)
{
}
