/*GENERATED BY OBNC 0.16.1*/

#include "extConvert.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "extConvert.obn"

void extConvert__IntToString_(OBNC_INTEGER i_, char s_[], OBNC_INTEGER s_len, int *done_)
{
}


void extConvert__RealToString_(OBNC_REAL x_, char s_[], OBNC_INTEGER s_len, int *done_)
{
}


void extConvert__StringToInt_(const char s_[], OBNC_INTEGER s_len, OBNC_INTEGER *i_, int *done_)
{
}


void extConvert__StringToReal_(const char s_[], OBNC_INTEGER s_len, OBNC_REAL *x_, int *done_)
{
}


void extConvert__Init(void)
{
}
