/*GENERATED BY OBNC 0.16.1*/

#ifndef extConvert_h
#define extConvert_h

#include <obnc/OBNC.h>

#define extConvert__IntToString_ ext__extConvert__IntToString_
void extConvert__IntToString_(OBNC_INTEGER i_, char s_[], OBNC_INTEGER s_len, int *done_);

#define extConvert__RealToString_ ext__extConvert__RealToString_
void extConvert__RealToString_(OBNC_REAL x_, char s_[], OBNC_INTEGER s_len, int *done_);

#define extConvert__StringToInt_ ext__extConvert__StringToInt_
void extConvert__StringToInt_(const char s_[], OBNC_INTEGER s_len, OBNC_INTEGER *i_, int *done_);

#define extConvert__StringToReal_ ext__extConvert__StringToReal_
void extConvert__StringToReal_(const char s_[], OBNC_INTEGER s_len, OBNC_REAL *x_, int *done_);

#define extConvert__Init ext__extConvert__Init
void extConvert__Init(void);

#endif
