/*GENERATED BY OBNC 0.16.1*/

#ifndef extErr_h
#define extErr_h

#include <obnc/OBNC.h>

#define extErr__Char_ ext__extErr__Char_
void extErr__Char_(char ch_);

#define extErr__String_ ext__extErr__String_
void extErr__String_(const char s_[], OBNC_INTEGER s_len);

#define extErr__Int_ ext__extErr__Int_
void extErr__Int_(OBNC_INTEGER i_, OBNC_INTEGER n_);

#define extErr__Hex_ ext__extErr__Hex_
void extErr__Hex_(OBNC_INTEGER i_);

#define extErr__Real_ ext__extErr__Real_
void extErr__Real_(OBNC_REAL x_, OBNC_INTEGER n_);

#define extErr__Ln_ ext__extErr__Ln_
void extErr__Ln_(void);

#define extErr__Init ext__extErr__Init
void extErr__Init(void);

#endif
