/*GENERATED BY OBNC 0.16.1*/

#ifndef extEnv_h
#define extEnv_h

#include <obnc/OBNC.h>

#define extEnv__Get_ ext__extEnv__Get_
void extEnv__Get_(const char name_[], OBNC_INTEGER name_len, char value_[], OBNC_INTEGER value_len, OBNC_INTEGER *res_);

#define extEnv__Init ext__extEnv__Init
void extEnv__Init(void);

#endif
