/*GENERATED BY OBNC 0.16.1*/

#include "extErr.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "extErr.obn"

void extErr__Char_(char ch_)
{
}


void extErr__String_(const char s_[], OBNC_INTEGER s_len)
{
}


void extErr__Int_(OBNC_INTEGER i_, OBNC_INTEGER n_)
{
}


void extErr__Hex_(OBNC_INTEGER i_)
{
}


void extErr__Real_(OBNC_REAL x_, OBNC_INTEGER n_)
{
}


void extErr__Ln_(void)
{
}


void extErr__Init(void)
{
}
