/*GENERATED BY OBNC 0.16.1*/

#include "extEnv.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "extEnv.obn"

void extEnv__Get_(const char name_[], OBNC_INTEGER name_len, char value_[], OBNC_INTEGER value_len, OBNC_INTEGER *res_)
{
}


void extEnv__Init(void)
{
}
