/*GENERATED BY OBNC 0.16.1*/

#include "extTrap.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "extTrap.obn"

extTrap__Handler_ extTrap__handle_;

void extTrap__SetHandler_(extTrap__Handler_ h_)
{
}


void extTrap__Init(void)
{
}
