/*GENERATED BY OBNC 0.16.1*/

#include <obnc/Out.h>
#include "extTrap.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "TrapTest.obn"

static OBNC_INTEGER i_;

static OBNC_INTEGER a_[10];

static void P_(OBNC_INTEGER exception_, const char file_[], OBNC_INTEGER file_len, OBNC_INTEGER line_)
{

	Out__String_("hello", 6);
	Out__Ln_();
}


#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	Out__Init();
	extTrap__Init();
	extTrap__SetHandler_(P_);
	i_ = 10;
	a_[OBNC_IT(i_, 10, 35)] = 0;
	return 0;
}
